default: &default
  adapter: sqlite3
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  # &primary_production を追加して、下の cable から参照できるようにします
  primary: &primary_production
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  # production.primary の設定をそのまま引き継ぎます
  cable:
    <<: *primary_production
    migrations_paths: db/cable_migrate